baseURL: "https://shreysahai.github.io/" 
title: Shrey Sahai Gupta
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Gallery
          url: gallery/
          weight: 5 
        - name: Publications
          url: publications/
          weight: 2
        - name: Teaching
          url: teaching/
          weight: 4
        - name: Research
          url: research/
          weight: 3 

params:
    description: "This website hosts Shrey's personal portfolio."
    author: Shrey Sahai Gupta
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "2006"
    defaultTheme: dark
    hideFooter: true
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["gallery","teaching","publications","research"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Shrey Sahai Gupta
          subtitle: " **Mechanical Engineer** | **Prime Minister Research Fellow** | **IISc Bangalore** | **IIT Ropar** 
          <br><br>
          I am a doctoral student in the Department of Mechanical Engineering at the Indian Institute of Science Bangalore. My research focuses on numerical control studies of supercritical Carbon Dioxide based Brayton power cycles."
          imageUrl: "picture.jpg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Publications
              url: publications/
            - name: Research
              url: research/
            - name: Gallery
              url: gallery/
            - name: Teaching
              url: teaching/
            - name: Tags
              url: tags/
            - name: Archive
              url: archive/

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: LinkedIn
          url: https://www.linkedin.com/in/shrey-sahai-gupta/
        - name: Email
          url: mailto:shreyg@iisc.ac.in
        - name: Location
          url: location/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=p0Nb_g0AAAAJ&hl=en&oi=ao
        - name: ResearchGate
          url: https://www.researchgate.net/profile/Shrey-Gupta-4?ev=hdr_xprf
        - name: GitHub
          url: https://github.com/ShreySahai
        - name: Twitter
          url: https://x.com/techscholarind

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Shrey Sahai Gupta"
      icon: favicon.ico
      iconHeight: 40

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2